version: '3.8'

# Define services
services:

  # App Service
  app:
    # Configuration for building the docker image for the service
    build:
      context: . # Use an image built from the specified dockerfile in the current directory.
      # dockerfile: Dockerfile
      dockerfile: ./go-dev.Dockerfile
    volumes:
    - '.:/app'
    ports:
      - "3000:3000"
    depends_on:
     - db

  db:
    image: mysql:latest
    container_name: mysqlDocker
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment: 

      MYSQL_ROOT_PASSWORD: "test"

      MYSQL_USER: "test"

      MYSQL_PASSWORD: "root"

      MYSQL_DATABASE: "demo"

    volumes: 

      - ./database_mysql:/var/lib/mysql

    cap_add: 

      - SYS_NICE

    healthcheck: 

      test: ["CMD-SHELL", "echo 'select 1' |mysql -u root -p'test' --silent"]

      interval: 30s

      timeout: 20s

      retries: 6
    ports: 
      - "3305:3306"
    expose: 
      - "3305"

volumes: 
    database_mysql:
networks:
    default:
        external:
            name: microservicenetwork